In [379]:
import pandas as pd
import numpy as np

import plotly
plotly.tools.set_credentials_file(username='jillianeb', api_key='eOsTljd6vVMiyuy4Msy0')
plotly.tools.set_config_file(world_readable=False,
                             sharing='private')

In [380]:
# read csv to df_orig
df_orig = pd.read_csv('/Users/jilliane/cse/viralseq_mapping/data/health_data.csv')

In [381]:
# change index to iso3 (3 letter country codes)
df_orig.columns = df_orig.iloc[3]

# for NaN values in iso3, replace with 'Global'
df_orig['iso3'] = df_orig['iso3'].replace(np.nan, 'Global', regex=True)

In [382]:
# copy original dataframe, excluding blank lines
df_withNA = df_orig[4:3319].copy()
df_withNA.index = df_withNA['iso3']

In [383]:
df_withNA

3,iso3,Country/area name,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,"4,003,141","6,047,778","307,725","1,466,299","1,774,025",2,11,14,8%,24%,18%
Global,Global,Global,2001,"3,902,504","5,851,905","294,644","1,406,326","1,700,971",2,11,13,8%,24%,17%
Global,Global,Global,2002,"3,800,435","5,547,240","282,158","1,348,396","1,630,553",2,10,12,7%,24%,17%
Global,Global,Global,2003,"3,699,679","5,421,280","270,859","1,291,699","1,562,558",2,10,12,7%,24%,17%
Global,Global,Global,2004,"3,601,737","5,163,989","259,239","1,241,529","1,500,768",2,9,11,7%,24%,17%
Global,Global,Global,2005,"3,505,159","4,928,527","246,933","1,192,271","1,439,204",2,9,11,7%,24%,17%
Global,Global,Global,2006,"3,415,328","4,660,282","235,214","1,155,132","1,390,346",2,9,10,7%,25%,17%
Global,Global,Global,2007,"3,323,929","4,409,248","223,953","1,107,225","1,331,178",2,8,10,7%,25%,17%
Global,Global,Global,2008,"3,236,930","4,265,929","214,501","1,056,833","1,271,334",2,8,9,7%,25%,17%
Global,Global,Global,2009,"3,153,926","4,115,455","205,889","1,013,537","1,219,426",1,7,9,7%,25%,17%
Global,Global,Global,2010,"3,070,191","3,943,044","197,625","972,561","1,170,186",1,7,8,6%,25%,17%
Global,Global,Global,2011,"2,986,799","3,769,835","190,382","931,079","1,121,461",1,7,8,6%,25%,17%
Global,Global,Global,2012,"2,906,294","3,579,147","183,010","882,694","1,065,704",1,6,8,6%,25%,16%
Global,Global,Global,2013,"2,827,927","3,460,642","175,950","830,535","1,006,486",1,6,7,6%,24%,16%
Global,Global,Global,2014,"2,752,570","3,300,736","169,580","782,358","951,938",1,6,7,6%,24%,16%
Global,Global,Global,2015,"2,678,550","3,180,926","163,490","742,157","905,647",1,5,6,6%,23%,15%
Global,Global,Global,2016,"2,612,443","3,036,996","159,416","719,413","878,829",1,5,6,6%,24%,16%
AFG,AFG,Afghanistan,2000,"60,864","66,493","4,389","18,498","22,888",4,19,23,7%,28%,18%
AFG,AFG,Afghanistan,2001,"61,385","70,623","4,500","18,844","23,345",4,18,23,7%,27%,18%
AFG,AFG,Afghanistan,2002,"61,688","63,490","4,610","18,946","23,556",4,18,22,7%,30%,19%
AFG,AFG,Afghanistan,2003,"61,799","56,422","4,721","19,003","23,723",4,18,22,8%,34%,20%
AFG,AFG,Afghanistan,2004,"61,605","55,930","4,775","18,924","23,699",4,17,22,8%,34%,20%
AFG,AFG,Afghanistan,2005,"61,178","56,448","4,701","18,612","23,313",4,17,21,8%,33%,20%
AFG,AFG,Afghanistan,2006,"60,372","60,085","4,558","18,259","22,817",4,16,20,8%,30%,19%
AFG,AFG,Afghanistan,2007,"59,296","53,419","4,397","17,559","21,956",4,15,19,7%,33%,19%
AFG,AFG,Afghanistan,2008,"57,979","51,716","4,228","16,602","20,830",4,15,18,7%,32%,19%
AFG,AFG,Afghanistan,2009,"56,355","51,983","4,052","15,375","19,427",4,13,17,7%,30%,18%
AFG,AFG,Afghanistan,2010,"54,723","48,546","3,868","14,299","18,168",3,13,16,7%,29%,18%
AFG,AFG,Afghanistan,2011,"52,931","46,770","3,679","13,453","17,132",3,12,15,7%,29%,17%
AFG,AFG,Afghanistan,2012,"51,274","44,313","3,518","12,821","16,339",3,11,14,7%,29%,17%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZMB,ZMB,Zambia,2004,"16,173","41,917","1,207","7,878","9,085",2,15,18,7%,19%,16%
ZMB,ZMB,Zambia,2005,"15,759","38,817","1,164","7,307","8,471",2,14,16,7%,19%,16%
ZMB,ZMB,Zambia,2006,"15,475","36,504","1,132","6,988","8,120",2,13,15,7%,19%,16%
ZMB,ZMB,Zambia,2007,"15,281","35,344","1,111","6,890","8,000",2,13,15,7%,19%,16%
ZMB,ZMB,Zambia,2008,"15,193","33,810","1,100","6,809","7,909",2,13,15,7%,20%,16%
ZMB,ZMB,Zambia,2009,"15,163","31,772","1,095","6,691","7,786",2,12,14,7%,21%,17%
ZMB,ZMB,Zambia,2010,"15,088","32,316","1,089","6,589","7,678",2,12,14,7%,20%,16%
ZMB,ZMB,Zambia,2011,"14,965","30,943","1,081","6,453","7,533",2,11,13,7%,21%,16%
ZMB,ZMB,Zambia,2012,"14,848","28,707","1,068","6,212","7,280",2,11,12,7%,22%,17%
ZMB,ZMB,Zambia,2013,"14,674","27,188","1,049","5,943","6,992",2,10,12,7%,22%,17%
ZMB,ZMB,Zambia,2014,"14,619","26,235","1,037","4,837","5,874",2,8,10,7%,18%,14%
ZMB,ZMB,Zambia,2015,"14,501","25,145","1,021","4,681","5,702",2,8,9,7%,19%,14%
ZMB,ZMB,Zambia,2016,"14,505","24,380","1,016","4,531","5,547",2,7,9,7%,19%,14%
ZWE,ZWE,Zimbabwe,2000,"10,847","27,287",774,"5,355","6,129",2,13,15,7%,20%,16%
ZWE,ZWE,Zimbabwe,2001,"11,145","27,776",798,"5,570","6,369",2,13,15,7%,20%,16%
ZWE,ZWE,Zimbabwe,2002,"11,521","28,405",829,"5,859","6,688",2,14,16,7%,21%,17%
ZWE,ZWE,Zimbabwe,2003,"11,977","28,725",865,"6,168","7,033",2,14,16,7%,21%,17%
ZWE,ZWE,Zimbabwe,2004,"12,513","29,509",907,"6,516","7,423",2,15,17,7%,22%,18%
ZWE,ZWE,Zimbabwe,2005,"13,087","30,325",951,"6,862","7,812",2,15,17,7%,23%,18%
ZWE,ZWE,Zimbabwe,2006,"13,653","31,118",992,"7,105","8,097",2,15,17,7%,23%,18%
ZWE,ZWE,Zimbabwe,2007,"14,201","31,284","1,030","6,616","7,646",2,14,16,7%,21%,17%
ZWE,ZWE,Zimbabwe,2008,"14,616","31,219","1,054","7,195","8,249",2,15,17,7%,23%,18%
ZWE,ZWE,Zimbabwe,2009,"14,874","30,778","1,064","6,780","7,843",2,14,16,7%,22%,17%
ZWE,ZWE,Zimbabwe,2010,"14,892","29,587","1,052","6,399","7,451",2,13,15,7%,22%,17%
ZWE,ZWE,Zimbabwe,2011,"14,744","27,604","1,029","6,170","7,199",2,12,14,7%,22%,17%
ZWE,ZWE,Zimbabwe,2012,"14,368","24,683",991,"5,522","6,513",2,10,12,7%,22%,17%
ZWE,ZWE,Zimbabwe,2013,"13,814","22,442",945,"4,133","5,078",2,8,10,7%,18%,14%
ZWE,ZWE,Zimbabwe,2014,"13,248","20,489",899,"3,814","4,714",2,7,9,7%,19%,14%
ZWE,ZWE,Zimbabwe,2015,"12,737","19,006",859,"3,713","4,572",2,7,9,7%,20%,14%
ZWE,ZWE,Zimbabwe,2016,"12,246","17,552",819,"3,555","4,374",2,7,8,7%,20%,15%

In [384]:
# remove entries with NaN or '-' values
print (df_withNA.shape)
df_withNA=df_withNA.replace('-', np.nan)
df = df_withNA.dropna(axis=0, how='any').fillna(0).copy()
print (df.shape)

(3315, 14)
(3279, 14)

In [385]:
df.columns

Index(['iso3', 'Country/area name', 'year', ' nnd ', ' pnd ', ' neo9 ',
       ' post9 ', ' ufive9 ', ' rneo9 ', ' rpost9 ', ' rufive9 ', 'fneo9',
       'fpost9', 'fufive9'],
      dtype='object', name=3)

In [386]:
# remove % sign for fneo9, fpost9 and fufive9
# '18' = 18%
df['fneo9'] = df['fneo9'].str.rstrip('%').astype('float')
df['fpost9'] = df['fpost9'].str.rstrip('%').astype('float')
df['fufive9'] = df['fufive9'].str.rstrip('%').astype('float')

df.head()

3,iso3,Country/area name,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,"4,003,141","6,047,778","307,725","1,466,299","1,774,025",2,11,14,8.0,24.0,18.0
Global,Global,Global,2001,"3,902,504","5,851,905","294,644","1,406,326","1,700,971",2,11,13,8.0,24.0,17.0
Global,Global,Global,2002,"3,800,435","5,547,240","282,158","1,348,396","1,630,553",2,10,12,7.0,24.0,17.0
Global,Global,Global,2003,"3,699,679","5,421,280","270,859","1,291,699","1,562,558",2,10,12,7.0,24.0,17.0
Global,Global,Global,2004,"3,601,737","5,163,989","259,239","1,241,529","1,500,768",2,9,11,7.0,24.0,17.0

In [387]:
df.dtypes

3
iso3                  object
Country/area name     object
year                  object
 nnd                  object
 pnd                  object
 neo9                 object
 post9                object
 ufive9               object
 rneo9                object
 rpost9               object
 rufive9              object
fneo9                float64
fpost9               float64
fufive9              float64
dtype: object

In [388]:
# # df[' nnd '] = df[' nnd '].str.strip().str.replace(',','').astype('int')
# # df[' pnd '] = df[' pnd '].str.strip().str.replace(',','').astype('int')
# #df[' neo9 '] = df[' neo9 '].str.strip().str.replace(',','').astype('int')
# #df[' post9 '] = df[' post9 '].str.strip().str.replace(',','').astype('int')
# df[' ufive9 '] = df[' ufive9 '].str.strip().str.replace(',','').astype('int')
# df[' rneo9 '] = df[' rneo9 '].str.strip().str.replace(',','').astype('int')
# df[' rpost9 '] = df[' rpost9 '].str.strip().str.replace(',','').astype('int')
# df[' rufive9 '] = df[' rufive9 '].str.strip().str.replace(',','').astype('int')


df.head()

3,iso3,Country/area name,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,"4,003,141","6,047,778","307,725","1,466,299","1,774,025",2,11,14,8.0,24.0,18.0
Global,Global,Global,2001,"3,902,504","5,851,905","294,644","1,406,326","1,700,971",2,11,13,8.0,24.0,17.0
Global,Global,Global,2002,"3,800,435","5,547,240","282,158","1,348,396","1,630,553",2,10,12,7.0,24.0,17.0
Global,Global,Global,2003,"3,699,679","5,421,280","270,859","1,291,699","1,562,558",2,10,12,7.0,24.0,17.0
Global,Global,Global,2004,"3,601,737","5,163,989","259,239","1,241,529","1,500,768",2,9,11,7.0,24.0,17.0

In [389]:
# remove spaces and commas from values in preparation to convert to numbers
df[' nnd '] = df[' nnd '].str.strip().str.replace(',','')
df[' pnd '] = df[' pnd '].str.strip().str.replace(',','')
df[' neo9 '] = df[' neo9 '].str.strip().str.replace(',','')
df[' post9 '] = df[' post9 '].str.strip().str.replace(',','')
df[' ufive9 '] = df[' ufive9 '].str.strip().str.replace(',','')
df[' rneo9 '] = df[' rneo9 '].str.strip().str.replace(',','')
df[' rpost9 '] = df[' rpost9 '].str.strip().str.replace(',','')
df[' rufive9 '] = df[' rufive9 '].str.strip().str.replace(',','')

In [390]:
df.head()

3,iso3,Country/area name,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,4003141,6047778,307725,1466299,1774025,2,11,14,8.0,24.0,18.0
Global,Global,Global,2001,3902504,5851905,294644,1406326,1700971,2,11,13,8.0,24.0,17.0
Global,Global,Global,2002,3800435,5547240,282158,1348396,1630553,2,10,12,7.0,24.0,17.0
Global,Global,Global,2003,3699679,5421280,270859,1291699,1562558,2,10,12,7.0,24.0,17.0
Global,Global,Global,2004,3601737,5163989,259239,1241529,1500768,2,9,11,7.0,24.0,17.0

In [391]:
df.dtypes

3
iso3                  object
Country/area name     object
year                  object
 nnd                  object
 pnd                  object
 neo9                 object
 post9                object
 ufive9               object
 rneo9                object
 rpost9               object
 rufive9              object
fneo9                float64
fpost9               float64
fufive9              float64
dtype: object

In [392]:
print (df.shape)
#df_withNA = df_withNA[df_withNA != '-']
df=df.replace('-', np.nan)
df_clean = df.dropna(axis=0, how='any').fillna(0).copy()
print (df_clean.shape)

(3279, 14)
(2996, 14)

In [393]:
# convert values to numbers
df_clean[' nnd '] = df_clean[' nnd '].astype('float')
df_clean[' pnd '] = df_clean[' pnd '].astype('float')
df_clean[' neo9 '] = df_clean[' neo9 '].astype('float')
df_clean[' post9 '] = df_clean[' post9 '].astype('float')
df_clean[' ufive9 '] = df_clean[' ufive9 '].astype('float')
df_clean[' rneo9 '] = df_clean[' rneo9 '].astype('float')
df_clean[' rpost9 '] = df_clean[' rpost9 '].astype('float')
df_clean[' rufive9 '] = df_clean[' rufive9 '].astype('float')

In [394]:
df_clean.columns

Index(['iso3', 'Country/area name', 'year', ' nnd ', ' pnd ', ' neo9 ',
       ' post9 ', ' ufive9 ', ' rneo9 ', ' rpost9 ', ' rufive9 ', 'fneo9',
       'fpost9', 'fufive9'],
      dtype='object', name=3)

In [395]:
df_clean.dtypes

3
iso3                  object
Country/area name     object
year                  object
 nnd                 float64
 pnd                 float64
 neo9                float64
 post9               float64
 ufive9              float64
 rneo9               float64
 rpost9              float64
 rufive9             float64
fneo9                float64
fpost9               float64
fufive9              float64
dtype: object

In [396]:
df_clean

3,iso3,Country/area name,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,4003141.0,6047778.0,307725.0,1466299.0,1774025.0,2.0,11.0,14.0,8.0,24.0,18.0
Global,Global,Global,2001,3902504.0,5851905.0,294644.0,1406326.0,1700971.0,2.0,11.0,13.0,8.0,24.0,17.0
Global,Global,Global,2002,3800435.0,5547240.0,282158.0,1348396.0,1630553.0,2.0,10.0,12.0,7.0,24.0,17.0
Global,Global,Global,2003,3699679.0,5421280.0,270859.0,1291699.0,1562558.0,2.0,10.0,12.0,7.0,24.0,17.0
Global,Global,Global,2004,3601737.0,5163989.0,259239.0,1241529.0,1500768.0,2.0,9.0,11.0,7.0,24.0,17.0
Global,Global,Global,2005,3505159.0,4928527.0,246933.0,1192271.0,1439204.0,2.0,9.0,11.0,7.0,24.0,17.0
Global,Global,Global,2006,3415328.0,4660282.0,235214.0,1155132.0,1390346.0,2.0,9.0,10.0,7.0,25.0,17.0
Global,Global,Global,2007,3323929.0,4409248.0,223953.0,1107225.0,1331178.0,2.0,8.0,10.0,7.0,25.0,17.0
Global,Global,Global,2008,3236930.0,4265929.0,214501.0,1056833.0,1271334.0,2.0,8.0,9.0,7.0,25.0,17.0
Global,Global,Global,2009,3153926.0,4115455.0,205889.0,1013537.0,1219426.0,1.0,7.0,9.0,7.0,25.0,17.0
Global,Global,Global,2010,3070191.0,3943044.0,197625.0,972561.0,1170186.0,1.0,7.0,8.0,6.0,25.0,17.0
Global,Global,Global,2011,2986799.0,3769835.0,190382.0,931079.0,1121461.0,1.0,7.0,8.0,6.0,25.0,17.0
Global,Global,Global,2012,2906294.0,3579147.0,183010.0,882694.0,1065704.0,1.0,6.0,8.0,6.0,25.0,16.0
Global,Global,Global,2013,2827927.0,3460642.0,175950.0,830535.0,1006486.0,1.0,6.0,7.0,6.0,24.0,16.0
Global,Global,Global,2014,2752570.0,3300736.0,169580.0,782358.0,951938.0,1.0,6.0,7.0,6.0,24.0,16.0
Global,Global,Global,2015,2678550.0,3180926.0,163490.0,742157.0,905647.0,1.0,5.0,6.0,6.0,23.0,15.0
Global,Global,Global,2016,2612443.0,3036996.0,159416.0,719413.0,878829.0,1.0,5.0,6.0,6.0,24.0,16.0
AFG,AFG,Afghanistan,2000,60864.0,66493.0,4389.0,18498.0,22888.0,4.0,19.0,23.0,7.0,28.0,18.0
AFG,AFG,Afghanistan,2001,61385.0,70623.0,4500.0,18844.0,23345.0,4.0,18.0,23.0,7.0,27.0,18.0
AFG,AFG,Afghanistan,2002,61688.0,63490.0,4610.0,18946.0,23556.0,4.0,18.0,22.0,7.0,30.0,19.0
AFG,AFG,Afghanistan,2003,61799.0,56422.0,4721.0,19003.0,23723.0,4.0,18.0,22.0,8.0,34.0,20.0
AFG,AFG,Afghanistan,2004,61605.0,55930.0,4775.0,18924.0,23699.0,4.0,17.0,22.0,8.0,34.0,20.0
AFG,AFG,Afghanistan,2005,61178.0,56448.0,4701.0,18612.0,23313.0,4.0,17.0,21.0,8.0,33.0,20.0
AFG,AFG,Afghanistan,2006,60372.0,60085.0,4558.0,18259.0,22817.0,4.0,16.0,20.0,8.0,30.0,19.0
AFG,AFG,Afghanistan,2007,59296.0,53419.0,4397.0,17559.0,21956.0,4.0,15.0,19.0,7.0,33.0,19.0
AFG,AFG,Afghanistan,2008,57979.0,51716.0,4228.0,16602.0,20830.0,4.0,15.0,18.0,7.0,32.0,19.0
AFG,AFG,Afghanistan,2009,56355.0,51983.0,4052.0,15375.0,19427.0,4.0,13.0,17.0,7.0,30.0,18.0
AFG,AFG,Afghanistan,2010,54723.0,48546.0,3868.0,14299.0,18168.0,3.0,13.0,16.0,7.0,29.0,18.0
AFG,AFG,Afghanistan,2011,52931.0,46770.0,3679.0,13453.0,17132.0,3.0,12.0,15.0,7.0,29.0,17.0
AFG,AFG,Afghanistan,2012,51274.0,44313.0,3518.0,12821.0,16339.0,3.0,11.0,14.0,7.0,29.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZMB,ZMB,Zambia,2004,16173.0,41917.0,1207.0,7878.0,9085.0,2.0,15.0,18.0,7.0,19.0,16.0
ZMB,ZMB,Zambia,2005,15759.0,38817.0,1164.0,7307.0,8471.0,2.0,14.0,16.0,7.0,19.0,16.0
ZMB,ZMB,Zambia,2006,15475.0,36504.0,1132.0,6988.0,8120.0,2.0,13.0,15.0,7.0,19.0,16.0
ZMB,ZMB,Zambia,2007,15281.0,35344.0,1111.0,6890.0,8000.0,2.0,13.0,15.0,7.0,19.0,16.0
ZMB,ZMB,Zambia,2008,15193.0,33810.0,1100.0,6809.0,7909.0,2.0,13.0,15.0,7.0,20.0,16.0
ZMB,ZMB,Zambia,2009,15163.0,31772.0,1095.0,6691.0,7786.0,2.0,12.0,14.0,7.0,21.0,17.0
ZMB,ZMB,Zambia,2010,15088.0,32316.0,1089.0,6589.0,7678.0,2.0,12.0,14.0,7.0,20.0,16.0
ZMB,ZMB,Zambia,2011,14965.0,30943.0,1081.0,6453.0,7533.0,2.0,11.0,13.0,7.0,21.0,16.0
ZMB,ZMB,Zambia,2012,14848.0,28707.0,1068.0,6212.0,7280.0,2.0,11.0,12.0,7.0,22.0,17.0
ZMB,ZMB,Zambia,2013,14674.0,27188.0,1049.0,5943.0,6992.0,2.0,10.0,12.0,7.0,22.0,17.0
ZMB,ZMB,Zambia,2014,14619.0,26235.0,1037.0,4837.0,5874.0,2.0,8.0,10.0,7.0,18.0,14.0
ZMB,ZMB,Zambia,2015,14501.0,25145.0,1021.0,4681.0,5702.0,2.0,8.0,9.0,7.0,19.0,14.0
ZMB,ZMB,Zambia,2016,14505.0,24380.0,1016.0,4531.0,5547.0,2.0,7.0,9.0,7.0,19.0,14.0
ZWE,ZWE,Zimbabwe,2000,10847.0,27287.0,774.0,5355.0,6129.0,2.0,13.0,15.0,7.0,20.0,16.0
ZWE,ZWE,Zimbabwe,2001,11145.0,27776.0,798.0,5570.0,6369.0,2.0,13.0,15.0,7.0,20.0,16.0
ZWE,ZWE,Zimbabwe,2002,11521.0,28405.0,829.0,5859.0,6688.0,2.0,14.0,16.0,7.0,21.0,17.0
ZWE,ZWE,Zimbabwe,2003,11977.0,28725.0,865.0,6168.0,7033.0,2.0,14.0,16.0,7.0,21.0,17.0
ZWE,ZWE,Zimbabwe,2004,12513.0,29509.0,907.0,6516.0,7423.0,2.0,15.0,17.0,7.0,22.0,18.0
ZWE,ZWE,Zimbabwe,2005,13087.0,30325.0,951.0,6862.0,7812.0,2.0,15.0,17.0,7.0,23.0,18.0
ZWE,ZWE,Zimbabwe,2006,13653.0,31118.0,992.0,7105.0,8097.0,2.0,15.0,17.0,7.0,23.0,18.0
ZWE,ZWE,Zimbabwe,2007,14201.0,31284.0,1030.0,6616.0,7646.0,2.0,14.0,16.0,7.0,21.0,17.0
ZWE,ZWE,Zimbabwe,2008,14616.0,31219.0,1054.0,7195.0,8249.0,2.0,15.0,17.0,7.0,23.0,18.0
ZWE,ZWE,Zimbabwe,2009,14874.0,30778.0,1064.0,6780.0,7843.0,2.0,14.0,16.0,7.0,22.0,17.0
ZWE,ZWE,Zimbabwe,2010,14892.0,29587.0,1052.0,6399.0,7451.0,2.0,13.0,15.0,7.0,22.0,17.0
ZWE,ZWE,Zimbabwe,2011,14744.0,27604.0,1029.0,6170.0,7199.0,2.0,12.0,14.0,7.0,22.0,17.0
ZWE,ZWE,Zimbabwe,2012,14368.0,24683.0,991.0,5522.0,6513.0,2.0,10.0,12.0,7.0,22.0,17.0
ZWE,ZWE,Zimbabwe,2013,13814.0,22442.0,945.0,4133.0,5078.0,2.0,8.0,10.0,7.0,18.0,14.0
ZWE,ZWE,Zimbabwe,2014,13248.0,20489.0,899.0,3814.0,4714.0,2.0,7.0,9.0,7.0,19.0,14.0
ZWE,ZWE,Zimbabwe,2015,12737.0,19006.0,859.0,3713.0,4572.0,2.0,7.0,9.0,7.0,20.0,14.0
ZWE,ZWE,Zimbabwe,2016,12246.0,17552.0,819.0,3555.0,4374.0,2.0,7.0,8.0,7.0,20.0,15.0

In [397]:
df.rename(columns={'Country/area name': 'country'}, inplace=True)
df.head()

3,iso3,country,year,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
iso3,,,,,,,,,,,,,,
Global,Global,Global,2000,4003141,6047778,307725,1466299,1774025,2,11,14,8.0,24.0,18.0
Global,Global,Global,2001,3902504,5851905,294644,1406326,1700971,2,11,13,8.0,24.0,17.0
Global,Global,Global,2002,3800435,5547240,282158,1348396,1630553,2,10,12,7.0,24.0,17.0
Global,Global,Global,2003,3699679,5421280,270859,1291699,1562558,2,10,12,7.0,24.0,17.0
Global,Global,Global,2004,3601737,5163989,259239,1241529,1500768,2,9,11,7.0,24.0,17.0

In [398]:
df.iloc[2]

3
iso3          Global
country       Global
year            2002
 nnd         3800435
 pnd         5547240
 neo9         282158
 post9       1348396
 ufive9      1630553
 rneo9             2
 rpost9           10
 rufive9          12
fneo9              7
fpost9            24
fufive9           17
Name: Global, dtype: object

In [399]:
country_codes = df.iso3.unique()
country_codes

array(['Global', 'AFG', 'AGO', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ATG',
       'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR',
       'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BOL', 'BRA', 'BRB', 'BRN',
       'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR',
       'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CYP',
       'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY',
       'ERI', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'FSM', 'GAB',
       'GBR', 'GEO', 'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD',
       'GTM', 'GUY', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL',
       'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ',
       'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN',
       'LBR', 'LBY', 'LCA', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAR',
       'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT',
       'MMR', 'MNE', 'MNG', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAM',
       'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN',
       'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRK', 'PRT',
       'PRY', 'QAT', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP',
       'SLB', 'SLE', 'SLV', 'SOM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK',
       'SVN', 'SWE', 'SWZ', 'SYC', 'SYR', 'TCD', 'TGO', 'THA', 'TJK',
       'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA',
       'UKR', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VNM', 'VUT', 'WSM',
       'YEM', 'ZAF', 'ZMB', 'ZWE'], dtype=object)

In [400]:
df['iso3'].unique()

array(['Global', 'AFG', 'AGO', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ATG',
       'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR',
       'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BOL', 'BRA', 'BRB', 'BRN',
       'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR',
       'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CYP',
       'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY',
       'ERI', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'FSM', 'GAB',
       'GBR', 'GEO', 'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD',
       'GTM', 'GUY', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL',
       'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ',
       'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN',
       'LBR', 'LBY', 'LCA', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAR',
       'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT',
       'MMR', 'MNE', 'MNG', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAM',
       'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN',
       'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRK', 'PRT',
       'PRY', 'QAT', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP',
       'SLB', 'SLE', 'SLV', 'SOM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK',
       'SVN', 'SWE', 'SWZ', 'SYC', 'SYR', 'TCD', 'TGO', 'THA', 'TJK',
       'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA',
       'UKR', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VNM', 'VUT', 'WSM',
       'YEM', 'ZAF', 'ZMB', 'ZWE'], dtype=object)

In [449]:
country_health_dict = dict(zip(df['iso3'].unique(), df['country'].unique()))

country_health_dict

{'Global': 'Global',
 'AFG': 'Afghanistan',
 'AGO': 'Angola',
 'ALB': 'Albania',
 'AND': 'Andorra',
 'ARE': 'United Arab Emirates',
 'ARG': 'Argentina',
 'ARM': 'Armenia',
 'ATG': 'Antigua and Barbuda',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'AZE': 'Azerbaijan',
 'BDI': 'Burundi',
 'BEL': 'Belgium',
 'BEN': 'Benin',
 'BFA': 'Burkina Faso',
 'BGD': 'Bangladesh',
 'BGR': 'Bulgaria',
 'BHR': 'Bahrain',
 'BHS': 'Bahamas',
 'BIH': 'Bosnia and Herzegovina',
 'BLR': 'Belarus',
 'BLZ': 'Belize',
 'BOL': 'Bolivia (Plurinational State of)',
 'BRA': 'Brazil',
 'BRB': 'Barbados',
 'BRN': 'Brunei Darussalam',
 'BTN': 'Bhutan',
 'BWA': 'Botswana',
 'CAF': 'Central African Republic',
 'CAN': 'Canada',
 'CHE': 'Switzerland',
 'CHL': 'Chile',
 'CHN': 'China',
 'CIV': "Cote d'Ivoire",
 'CMR': 'Cameroon',
 'COD': 'Democratic Republic of the Congo',
 'COG': 'Congo',
 'COK': 'Cook Islands',
 'COL': 'Colombia',
 'COM': 'Comoros',
 'CPV': 'Cabo Verde',
 'CRI': 'Costa Rica',
 'CUB': 'Cuba',
 'CYP': 'Cyprus',
 'CZE': 'Czechia',
 'DEU': 'Germany',
 'DJI': 'Djibouti',
 'DMA': 'Dominica',
 'DNK': 'Denmark',
 'DOM': 'Dominican Republic',
 'DZA': 'Algeria',
 'ECU': 'Ecuador',
 'EGY': 'Egypt',
 'ERI': 'Eritrea',
 'ESP': 'Spain',
 'EST': 'Estonia',
 'ETH': 'Ethiopia',
 'FIN': 'Finland',
 'FJI': 'Fiji',
 'FRA': 'France',
 'FSM': 'Micronesia (Federated States of)',
 'GAB': 'Gabon',
 'GBR': 'United Kingdom',
 'GEO': 'Georgia',
 'GHA': 'Ghana',
 'GIN': 'Guinea',
 'GMB': 'Gambia',
 'GNB': 'Guinea-Bissau',
 'GNQ': 'Equatorial Guinea',
 'GRC': 'Greece',
 'GRD': 'Grenada',
 'GTM': 'Guatemala',
 'GUY': 'Guyana',
 'HND': 'Honduras',
 'HRV': 'Croatia',
 'HTI': 'Haiti',
 'HUN': 'Hungary',
 'IDN': 'Indonesia',
 'IND': 'India',
 'IRL': 'Ireland',
 'IRN': 'Iran (Islamic Republic of)',
 'IRQ': 'Iraq',
 'ISL': 'Iceland',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'JAM': 'Jamaica',
 'JOR': 'Jordan',
 'JPN': 'Japan',
 'KAZ': 'Kazakhstan',
 'KEN': 'Kenya',
 'KGZ': 'Kyrgyzstan',
 'KHM': 'Cambodia',
 'KIR': 'Kiribati',
 'KNA': 'Saint Kitts and Nevis',
 'KOR': 'Republic of Korea',
 'KWT': 'Kuwait',
 'LAO': "Lao People's Democratic Republic",
 'LBN': 'Lebanon',
 'LBR': 'Liberia',
 'LBY': 'Libya',
 'LCA': 'Saint Lucia',
 'LKA': 'Sri Lanka',
 'LSO': 'Lesotho',
 'LTU': 'Lithuania',
 'LUX': 'Luxembourg',
 'LVA': 'Latvia',
 'MAR': 'Morocco',
 'MCO': 'Monaco',
 'MDA': 'Republic of Moldova',
 'MDG': 'Madagascar',
 'MDV': 'Maldives',
 'MEX': 'Mexico',
 'MHL': 'Marshall Islands',
 'MKD': 'The former Yugoslav Republic of Macedonia',
 'MLI': 'Mali',
 'MLT': 'Malta',
 'MMR': 'Myanmar',
 'MNE': 'Montenegro',
 'MNG': 'Mongolia',
 'MOZ': 'Mozambique',
 'MRT': 'Mauritania',
 'MUS': 'Mauritius',
 'MWI': 'Malawi',
 'MYS': 'Malaysia',
 'NAM': 'Namibia',
 'NER': 'Niger',
 'NGA': 'Nigeria',
 'NIC': 'Nicaragua',
 'NLD': 'Netherlands',
 'NOR': 'Norway',
 'NPL': 'Nepal',
 'NRU': 'Nauru',
 'NZL': 'New Zealand',
 'OMN': 'Oman',
 'PAK': 'Pakistan',
 'PAN': 'Panama',
 'PER': 'Peru',
 'PHL': 'Philippines',
 'PLW': 'Palau',
 'PNG': 'Papua New Guinea',
 'POL': 'Poland',
 'PRK': "Democratic People's Republic of Korea",
 'PRT': 'Portugal',
 'PRY': 'Paraguay',
 'QAT': 'Qatar',
 'ROU': 'Romania',
 'RUS': 'Russian Federation',
 'RWA': 'Rwanda',
 'SAU': 'Saudi Arabia',
 'SDN': 'Sudan',
 'SEN': 'Senegal',
 'SGP': 'Singapore',
 'SLB': 'Solomon Islands',
 'SLE': 'Sierra Leone',
 'SLV': 'El Salvador',
 'SOM': 'Somalia',
 'SRB': 'Serbia',
 'SSD': 'South Sudan',
 'STP': 'Sao Tome and Principe',
 'SUR': 'Suriname',
 'SVK': 'Slovakia',
 'SVN': 'Slovenia',
 'SWE': 'Sweden',
 'SWZ': 'Swaziland',
 'SYC': 'Seychelles',
 'SYR': 'Syrian Arab Republic',
 'TCD': 'Chad',
 'TGO': 'Togo',
 'THA': 'Thailand',
 'TJK': 'Tajikistan',
 'TKM': 'Turkmenistan',
 'TLS': 'Timor-Leste',
 'TON': 'Tonga',
 'TTO': 'Trinidad and Tobago',
 'TUN': 'Tunisia',
 'TUR': 'Turkey',
 'TUV': 'Tuvalu',
 'TZA': 'United Republic of Tanzania',
 'UGA': 'Uganda',
 'UKR': 'Ukraine',
 'URY': 'Uruguay',
 'USA': 'United States of America',
 'UZB': 'Uzbekistan',
 'VCT': 'Saint Vincent and the Grenadines',
 'VEN': 'Venezuela (Bolivarian Republic of)',
 'VNM': 'Viet Nam',
 'VUT': 'Vanuatu',
 'WSM': 'Samoa',
 'YEM': 'Yemen',
 'ZAF': 'South Africa',
 'ZMB': 'Zambia',
 'ZWE': 'Zimbabwe'}

In [402]:
#df.to_csv('health_data_cleaned.csv')

In [403]:
df.dtypes

3
iso3          object
country       object
year          object
 nnd          object
 pnd          object
 neo9         object
 post9        object
 ufive9       object
 rneo9        object
 rpost9       object
 rufive9      object
fneo9        float64
fpost9       float64
fufive9      float64
dtype: object

In [404]:
# create summary dataframe to groupby iso3 and calculate the mean 
# note: maybe change to median??
df_summary = df_clean.groupby(df_clean.index).mean().reset_index()
df_summary

3,iso3,nnd,pnd,neo9,post9,ufive9,rneo9,rpost9,rufive9,fneo9,fpost9,fufive9
0,AFG,56014.352941,51309.941176,4052.352941,15539.117647,19591.588235,3.588235,14.117647,17.705882,7.235294,30.294118,18.117647
1,AGO,39491.470588,91787.705882,2980.647059,23473.294118,26454.058824,3.058824,24.117647,27.235294,7.882353,25.529412,20.058824
2,ALB,340.000000,418.176471,30.588235,82.058824,112.588235,0.764706,2.000000,2.823529,8.647059,18.117647,13.764706
3,ARE,364.470588,321.000000,2.647059,30.941176,33.588235,0.000000,0.176471,0.235294,1.000000,9.705882,5.117647
4,ARG,6289.823529,4937.176471,113.823529,713.764706,827.470588,0.000000,1.000000,1.058824,1.764706,14.352941,7.411765
5,ARM,470.000000,389.588235,40.705882,85.529412,126.117647,1.058824,2.000000,3.000000,8.235294,20.823529,14.000000
6,ATG,11.000000,8.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,4.000000,9.666667,6.333333
7,AUS,826.857143,591.928571,2.428571,39.071429,41.571429,0.000000,0.000000,0.000000,0.071429,6.714286,2.928571
8,AUT,229.250000,174.750000,1.500000,7.000000,8.500000,0.000000,0.000000,0.000000,0.250000,4.250000,2.250000
9,AZE,3761.352941,3240.235294,209.000000,939.352941,1148.235294,1.352941,6.294118,7.764706,5.470588,28.411765,15.941176
10,BDI,10787.352941,24725.529412,818.352941,5488.529412,6306.941176,2.411765,16.235294,18.470588,7.470588,22.176471,17.705882
11,BEL,307.461538,273.769231,1.769231,10.000000,11.923077,0.000000,0.000000,0.000000,0.538462,3.769231,2.153846
12,BEN,12041.294118,27223.411765,769.705882,5627.117647,6396.882353,2.117647,16.588235,18.764706,6.235294,20.764706,16.235294
13,BFA,20760.647059,60001.352941,1383.352941,7882.176471,9265.411765,2.294118,12.647059,14.764706,6.764706,13.470588,11.705882
14,BGD,103788.294118,95066.705882,7376.000000,29605.529412,36981.529412,2.117647,8.705882,10.941176,6.882353,30.941176,18.176471
15,BGR,382.058824,442.647059,24.941176,137.941176,162.882353,0.176471,2.000000,2.411765,6.352941,30.000000,19.117647
16,BHR,64.600000,103.800000,0.800000,4.000000,5.000000,0.000000,0.000000,0.000000,1.800000,3.800000,3.000000
17,BHS,40.941176,35.000000,5.764706,6.764706,12.411765,1.176471,1.235294,2.411765,13.529412,19.411765,16.294118
18,BIH,188.176471,88.411765,9.176471,11.411765,20.647059,0.000000,0.235294,0.529412,4.705882,11.705882,7.058824
19,BLR,290.000000,415.882353,13.764706,56.764706,70.647059,0.000000,0.470588,0.647059,4.294118,12.705882,9.235294
20,BLZ,95.882353,52.117647,3.529412,9.058824,12.647059,0.352941,1.352941,1.588235,3.647059,16.470588,8.470588
21,BOL,6192.823529,7591.823529,401.588235,1934.058824,2335.882353,1.529412,7.529412,9.176471,6.411765,25.235294,16.588235
22,BRA,38033.352941,37302.470588,908.058824,6883.352941,7791.470588,0.058824,2.058824,2.470588,2.294118,18.000000,10.058824
23,BRB,34.000000,21.000000,1.000000,3.000000,3.666667,0.000000,1.000000,1.000000,2.000000,14.666667,6.666667
24,BRN,31.470588,41.058824,0.882353,3.235294,3.705882,0.000000,0.411765,0.705882,1.882353,7.764706,5.235294
25,BTN,370.823529,410.823529,22.117647,128.411765,150.764706,1.411765,8.411765,9.882353,5.823529,30.764706,18.588235
26,BWA,1400.941176,1626.764706,84.000000,197.058824,281.117647,1.941176,4.117647,5.647059,6.000000,13.647059,9.588235
27,CAF,7623.294118,16854.764706,559.411765,2961.882353,3521.235294,3.470588,18.176471,21.588235,7.000000,17.764706,14.588235
28,CAN,1343.117647,715.941176,4.058824,32.058824,36.058824,0.000000,0.000000,0.000000,0.058824,4.588235,1.823529
29,CHE,251.529412,121.294118,1.294118,4.294118,5.705882,0.000000,0.000000,0.000000,0.823529,3.588235,1.470588
...,...,...,...,...,...,...,...,...,...,...,...,...
157,SWE,193.909091,159.090909,2.636364,9.636364,12.363636,0.000000,0.000000,0.000000,1.363636,6.000000,3.636364
158,SWZ,829.764706,2855.294118,56.764706,498.352941,555.117647,1.529412,13.470588,15.176471,6.823529,17.882353,15.235294
159,SYC,14.705882,8.470588,0.235294,1.000000,1.882353,0.000000,1.000000,1.000000,3.058824,14.352941,7.470588
160,SYR,5005.000000,4444.470588,240.235294,799.176471,1039.176471,0.235294,1.470588,2.176471,5.000000,17.705882,10.764706
161,TCD,20679.647059,58081.117647,1743.588235,16496.941176,18240.411765,3.176471,31.352941,34.705882,8.411765,28.470588,23.176471
162,TGO,7048.705882,14418.000000,514.470588,2563.352941,3077.823529,2.117647,11.117647,13.235294,7.000000,17.823529,14.352941
163,THA,8246.823529,5630.941176,418.529412,953.176471,1371.764706,0.411765,1.176471,1.588235,4.882353,16.647059,9.588235
164,TJK,5152.588235,7438.058824,329.529412,2189.647059,2519.235294,1.529412,10.470588,12.058824,6.235294,29.117647,19.882353
165,TKM,3229.588235,4641.411765,194.294118,1311.000000,1505.235294,1.647059,10.882353,12.647059,6.000000,28.176471,19.058824
166,TLS,1153.764706,1807.294118,88.647059,584.294118,673.000000,2.235294,14.235294,16.470588,7.705882,32.470588,22.588235
167,TON,19.882353,27.411765,1.000000,4.117647,5.235294,0.000000,1.294118,2.000000,6.000000,15.235294,11.294118
168,TTO,307.764706,147.941176,15.294118,15.235294,30.294118,0.882353,0.941176,1.588235,5.117647,10.411765,6.588235
169,TUN,2218.117647,1461.411765,122.647059,282.588235,405.411765,0.588235,1.647059,2.235294,5.352941,18.470588,10.529412
170,TUR,15497.411765,15711.823529,232.352941,1405.294118,1637.647059,0.000000,1.000000,1.294118,1.588235,8.235294,4.941176
171,TUV,5.294118,2.705882,0.117647,0.647059,1.235294,1.411765,3.176471,4.588235,6.705882,27.352941,13.647059
172,TZA,47125.764706,94533.941176,3517.647059,22159.529412,25677.176471,2.117647,12.823529,14.882353,7.411765,23.411765,17.882353
173,UGA,38615.470588,99099.235294,2816.176471,17497.294118,20313.588235,2.058824,12.529412,14.470588,7.352941,18.588235,15.000000
174,UKR,3536.941176,2317.764706,251.764706,381.000000,632.823529,0.529412,0.941176,1.411765,7.058824,15.882353,10.529412
175,URY,326.058824,317.823529,5.176471,48.058824,53.117647,0.000000,0.823529,1.000000,1.411765,14.352941,7.764706
176,USA,17164.529412,13294.352941,97.588235,815.705882,913.294118,0.000000,0.000000,0.000000,0.588235,6.058824,3.000000
177,UZB,12858.235294,12233.647059,731.176471,3419.705882,4151.000000,1.235294,5.764706,7.000000,5.764706,27.352941,16.117647
178,VCT,23.100000,13.900000,0.400000,1.200000,2.000000,0.100000,0.800000,1.100000,2.100000,10.900000,5.500000
179,VEN,6263.882353,4504.882353,345.411765,720.000000,1065.411765,0.647059,1.058824,2.000000,5.588235,16.058824,9.823529
180,VNM,19072.647059,17673.411765,1621.235294,3650.058824,5271.000000,1.000000,2.470588,3.588235,8.470588,20.470588,14.294118
181,VUT,78.176471,103.823529,5.823529,20.529412,26.411765,1.000000,3.058824,4.000000,7.470588,19.647059,14.352941
182,WSM,53.588235,48.470588,2.764706,7.000000,9.823529,0.764706,1.235294,2.117647,5.058824,14.294118,9.470588
183,YEM,23713.588235,28255.058824,1766.176471,8436.176471,10202.352941,2.294118,10.882353,13.176471,7.529412,29.529412,19.529412
184,ZAF,15382.235294,53325.411765,1139.294118,7723.000000,8862.294118,1.000000,6.764706,7.647059,7.117647,15.294118,13.294118
185,ZMB,15574.117647,36635.352941,1138.529412,7135.058824,8273.529412,2.176471,13.411765,15.529412,7.235294,19.588235,15.823529
186,ZWE,13204.882353,26928.764706,932.823529,5725.411765,6658.235294,2.000000,12.117647,14.058824,7.000000,21.117647,16.470588

In [405]:
# export summary dataframe to csv
#df_summary.to_csv('health_data_summary_cleaned.csv')

In [406]:
df_genotypes = pd.read_csv('/Users/jilliane/cse/viralseq_mapping/data/RSVG_gb_metadata.csv')

print (df_genotypes.shape)

(5000, 19)

In [463]:
genotype_full = df_genotypes['country'].unique().tolist()

In [407]:
df_genotypes['country_only'] = df_genotypes['country'].str.split(':').str[0]
print (df_genotypes.shape)

df_genotypes.head()

(5000, 20)

,Unnamed: 0,collection_date,country,db_xref,genotype,host,isolate,isolation_source,mol_type,note,organism,strain,subtype,lat_lon,collected_by,serotype,clone,PCR_primers,lab_host,country_only
0,0,15-Apr-2010,Kenya,taxon:208895,NaN,Homo sapiens,NaN,NaN,viral cRNA,NaN,Human respiratory syncytial virus B,Kilifi/HH/4501/15-Apr-2010,B,NaN,NaN,NaN,NaN,NaN,NaN,Kenya
1,1,18-Mar-2010,Kenya,taxon:208895,NaN,Homo sapiens,NaN,NaN,viral cRNA,NaN,Human respiratory syncytial virus B,Kilifi/HH/2605/18-Mar-2010,B,NaN,NaN,NaN,NaN,NaN,NaN,Kenya
2,2,05-Apr-2010,Kenya,taxon:208895,NaN,Homo sapiens,NaN,NaN,viral cRNA,NaN,Human respiratory syncytial virus B,Kilifi/HH/2502/05-Apr-2010,B,NaN,NaN,NaN,NaN,NaN,NaN,Kenya
3,3,04-Mar-2010,Kenya,taxon:208895,NaN,Homo sapiens,NaN,NaN,viral cRNA,NaN,Human respiratory syncytial virus B,Kilifi/HH/1911/04-Mar-2010,B,NaN,NaN,NaN,NaN,NaN,NaN,Kenya
4,4,20-Apr-2010,Kenya,taxon:208895,NaN,Homo sapiens,NaN,NaN,viral cRNA,NaN,Human respiratory syncytial virus B,Kilifi/HH/1903/20-Apr-2010,B,NaN,NaN,NaN,NaN,NaN,NaN,Kenya

In [414]:
country_geno = df_genotypes['country_only'].dropna()
# country_geno_uniques.delete(nan, index)
country_geno_uniques = country_geno.unique().tolist()
country_geno_uniques

['Kenya',
 'Cameroon',
 'Russia',
 'Australia',
 'Ghana',
 'Malaysia',
 'Myanmar',
 'Lebanon',
 'Japan',
 'Philippines',
 'India',
 'Argentina',
 'Laos',
 'Saudi Arabia',
 'China',
 'Spain',
 'Germany',
 'Nigeria',
 'Egypt',
 'Mexico',
 'USA',
 'Turkey',
 'Croatia',
 'Brazil',
 'Panama',
 'Guatemala',
 'South Korea',
 'Colombia',
 'Thailand',
 'France',
 'Taiwan',
 'Italy']

In [412]:
import country_converter as coco

In [428]:


# for i in country_geno_uniques:
#     country_list.append(coco.convert(names=i, to='ISO3'))
geno_countries = coco.convert(names=country_geno_uniques, to='ISO3')
geno_countries

['KEN',
 'CMR',
 'RUS',
 'AUS',
 'GHA',
 'MYS',
 'MMR',
 'LBN',
 'JPN',
 'PHL',
 'IND',
 'ARG',
 'LAO',
 'SAU',
 'CHN',
 'ESP',
 'DEU',
 'NGA',
 'EGY',
 'MEX',
 'USA',
 'TUR',
 'HRV',
 'BRA',
 'PAN',
 'GTM',
 'KOR',
 'COL',
 'THA',
 'FRA',
 'TWN',
 'ITA']

In [423]:
# take input country name and convert to ISO3
import country_converter as coco
coco.convert(names='Italy', to='ISO3')

'ITA'

In [464]:
coco.convert(names=genotype_full, to='ISO3')

WARNING:root:nan not found in ISO3
WARNING:root:USA: Rochester, NY not found in regex
WARNING:root:USA: Connecticut not found in regex
WARNING:root:USA: Texas not found in regex
WARNING:root:USA: Tennessee not found in regex

['KEN',
 'not found',
 'CMR',
 'RUS',
 'AUS',
 'GHA',
 'MYS',
 'MMR',
 'MMR',
 'LBN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'JPN',
 'PHL',
 'IND',
 'ARG',
 'LAO',
 'SAU',
 'CHN',
 'ESP',
 'DEU',
 'NGA',
 'EGY',
 'MEX',
 'USA',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'EGY',
 'TUR',
 'HRV',
 'BRA',
 'not found',
 'PAN',
 'GTM',
 'KOR',
 'COL',
 'THA',
 'JPN',
 'not found',
 'not found',
 'not found',
 'FRA',
 'TWN',
 'ITA',
 'BRA']

In [448]:
# find value in the genotype data not in the health data
# Taiwan is not included in health data 
np.setdiff1d(geno_countries,country_codes)

array(['TWN'], dtype='<U3')

In [455]:
country_dict = dict(zip(geno_countries, country_geno_uniques))

#country_dict

In [457]:
# with this dictionary:
# 1) take input text from user
# 2) convert that to ISO3 using coco (see above)
# 3a) ISO3 can then access the health data directly
# 3b) use the country_dict to convert ISO3 to the country used in the genotype data
# 3b-2) then use that country to access the genotype data


country_dict['KEN']

'Kenya'

Done:
- processed health data: now can output csv file of all data (cleaned) or summary data on a per-country basis
- found python package capable of taking all country inputs found in the genotype dataset and converting that to ISO3 values to access health data

To do:
- write scripts to output graph for:
- no specifications - what summary data to show?
- country specified - show only that data OR show that country's data highlighted
    (also handle when the country is not included in the dataset - show global data?)
- specific data is requested (how to best graph each column? how to graph multiple columns at once?)
- add option for a) highlight one country with the full dataset shown or b) show just data for that country across the years included